version: '3.7'

services:
  # startup web
  web:
    build: .
    image: app
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  # db for django app (default)
  db:
    image: mysql:5.7
    command: --init-file /data/init_django_db.sql
    volumes:
        - ./init/init_django_db.sql:/data/init_django_db.sql
        - ./dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
